import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const resendApiKey = Deno.env.get('RESEND_API_KEY')

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    if (!resendApiKey) {
      throw new Error("RESEND_API_KEY is not set in edge function environment.");
    }

    const { to, account_name, rows } = await req.json()

    if (!to || !account_name || !rows) {
      throw new Error("Missing required parameters: 'to', 'account_name', or 'rows'");
    }

    // Build HTML table for the statement
    const tableRows = rows.map((r: any) => `
      <tr>
        <td style="padding: 8px; border: 1px solid #ddd;">${r.date || ''}</td>
        <td style="padding: 8px; border: 1px solid #ddd;">${r.code || ''}</td>
        <td style="padding: 8px; border: 1px solid #ddd;">${r.details || ''}</td>
        <td style="padding: 8px; border: 1px solid #ddd; color: #d9534f; text-align: right;">${r.debit > 0 ? r.debit : ''}</td>
        <td style="padding: 8px; border: 1px solid #ddd; color: #5cb85c; text-align: right;">${r.credit > 0 ? r.credit : ''}</td>
        <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold; text-align: right;">${r.balance}</td>
      </tr>
    `).join('');

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; color: #333; max-width: 800px; margin: 0 auto;">
        <h2 style="color: #4f46e5;">Account Statement: ${account_name}</h2>
        <p>Please find the requested account statement below.</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          <thead>
            <tr style="background-color: #f8f9fa;">
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Date</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Code</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Details</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: right;">Debit</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: right;">Credit</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: right;">Balance</th>
            </tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>
        <p style="margin-top: 30px; font-size: 12px; color: #777;">Generated by Asaan Khata</p>
      </div>
    `;

    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${resendApiKey}`,
      },
      body: JSON.stringify({
        from: 'Asaan Khata <onboarding@resend.dev>', // resend.dev is allowed for testing
        to: [to],
        subject: `Account Statement - ${account_name}`,
        html: htmlContent,
      }),
    })

    const data = await res.json()

    if (!res.ok) {
      throw new Error(data.message || 'Failed to send email via Resend')
    }

    return new Response(JSON.stringify({ success: true, data }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    })
  } catch (error: any) {
    return new Response(JSON.stringify({ success: false, error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    })
  }
})
