// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  logger.error("Supabase configuration missing! Check your environment variables.");
}

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co", 
  SUPABASE_PUBLISHABLE_KEY || "placeholder", 
  {
    global: {
      fetch: async (url, options = {}) => {
        // @ts-expect-error - window.Clerk is injected by ClerkProvider
        const clerkToken = typeof window !== 'undefined' && window.Clerk?.session
          // @ts-expect-error - window.Clerk.session.getToken is injected at runtime
          ? await window.Clerk.session.getToken({ template: 'supabase' })
          : null;
        
        const headers = new Headers(options?.headers);
        if (clerkToken) {
          headers.set('Authorization', `Bearer ${clerkToken}`);
        }
        
        return fetch(url, { ...options, headers });
      }
    }
  }
);